#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

pull-docker-image() {
  declare IMAGE="$1"
  if [[ "$(docker images -q "${IMAGE}" 2> /dev/null)" == "" ]]; then
    docker pull "${IMAGE}"
  fi
}

pull-docker-image "${PLUGIN_IMAGE}:${PLUGIN_IMAGE_VERSION}"
pull-docker-image "svendowideit/ambassador:latest"
pull-docker-image "dokkupaas/wait:0.2"

mkdir -p "$PLUGIN_DATA_ROOT" || echo "Failed to create $PLUGIN_SERVICE directory"
chown dokku:dokku "$PLUGIN_DATA_ROOT"

echo "%dokku ALL=(ALL) NOPASSWD:/bin/chown 8983 $PLUGIN_DATA_ROOT/*" > /etc/sudoers.d/dokku-solr-chown
echo "%dokku ALL=(ALL) NOPASSWD:/bin/chgrp 8983 $PLUGIN_DATA_ROOT/*" > /etc/sudoers.d/dokku-solr-chgrp
chmod 0440 /etc/sudoers.d/dokku-solr-chown
chmod 0440 /etc/sudoers.d/dokku-solr-chgrp
