#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

solr-post-extract() {
  declare APP="$1" TMPDIR="$2"
  local LINKED_SERVICES SERVICE SERVICE_CONTAINER_ID SERVICE_ROOT TMPDIR

  LINKED_SERVICES="$(solr-linked-services "$APP")"

  if [[ -z $LINKED_SERVICES ]]; then
    return
  fi

  if [[ -d "${TMPDIR}/solr" ]]; then
    for SERVICE in $LINKED_SERVICES; do
      dokku_log_info1_quiet "Copying solr to service conf"
      SERVICE_ROOT="${PLUGIN_DATA_ROOT}/${SERVICE}"
      SERVICE_CONTAINER_ID="$(cat "$SERVICE_ROOT/ID")"
      for f in ${TMPDIR}/solr/*; do docker cp $f "${SERVICE_CONTAINER_ID}:/opt/solr/server/solr/mycores/${SERVICE}/conf/"; done
      sudo /bin/chown 8983 "${SERVICE_ROOT}/data/${SERVICE}/conf/"*
      sudo /bin/chgrp 8983 "${SERVICE_ROOT}/data/${SERVICE}/conf/"*
    done
  fi
}

solr-linked-services() {
  declare APP="$1"
  local LINKS_FILE SERVICES SERVICE_ROOT
  SERVICES=$(ls "$PLUGIN_DATA_ROOT" 2>/dev/null)

  for SERVICE in $SERVICES; do
    SERVICE_ROOT="${PLUGIN_DATA_ROOT}/${SERVICE}"
    LINKS_FILE="${SERVICE_ROOT}/LINKS"

    if grep -Fxq "$APP" "$LINKS_FILE" >/dev/null; then
      echo -n "${SERVICE} "
    fi
  done
}

solr-post-extract "$@"
