#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

solr-post-extract() {
  declare APP="$1" TMPDIR="$2"
  local LINKED_SERVICES SERVICE SERVICE_CONTAINER_ID SERVICE_ROOT TMPDIR

  LINKED_SERVICES="$(solr-linked-services "$APP")"

  if [[ -z $LINKED_SERVICES ]]; then
    return
  fi

  if [[ -f "${TMPDIR}/solr/schema.xml" ]]; then
    for SERVICE in $LINKED_SERVICES; do
      dokku_log_info1_quiet "Copying solr/schema.xml to service conf/schema.xml"
      SERVICE_ROOT="${PLUGIN_DATA_ROOT}/${SERVICE}"
      SERVICE_CONTAINER_ID="$(cat "$SERVICE_ROOT/ID")"
      docker cp "${TMPDIR}/solr/schema.xml" "${SERVICE_CONTAINER_ID}:/var/solr/data/${SERVICE}/conf/schema.xml"
      sudo /bin/chown 8983 "${SERVICE_ROOT}/data/${SERVICE}/conf/schema.xml"
      sudo /bin/chgrp 8983 "${SERVICE_ROOT}/data/${SERVICE}/conf/schema.xml"
    done
  fi

  if [[ -f "${TMPDIR}/solr/solrconfig.xml" ]]; then
    for SERVICE in $LINKED_SERVICES; do
      dokku_log_info1_quiet "Copying solr/solrconfig.xml to service' conf/solrconfig.xml"
      SERVICE_ROOT="${PLUGIN_DATA_ROOT}/${SERVICE}"
      SERVICE_CONTAINER_ID="$(cat "$SERVICE_ROOT/ID")"
      docker cp "${TMPDIR}/solr/solrconfig.xml" "${SERVICE_CONTAINER_ID}:/var/solr/data/${SERVICE}/conf/solrconfig.xml"
      sudo /bin/chown 8983 "${SERVICE_ROOT}/data/${SERVICE}/conf/solrconfig.xml"
      sudo /bin/chgrp 8983 "${SERVICE_ROOT}/data/${SERVICE}/conf/solrconfig.xml"
    done
  fi
}

solr-linked-services() {
  declare APP="$1"
  local LINKS_FILE SERVICES SERVICE_ROOT
  SERVICES=$(ls "$PLUGIN_DATA_ROOT" 2>/dev/null)

  for SERVICE in $SERVICES; do
    SERVICE_ROOT="${PLUGIN_DATA_ROOT}/${SERVICE}"
    LINKS_FILE="${SERVICE_ROOT}/LINKS"

    if grep -Fxq "$APP" "$LINKS_FILE" >/dev/null; then
      echo -n "${SERVICE} "
    fi
  done
}

solr-post-extract "$@"
